spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENTID}
            clientSecret: ${GITHUB_CLIENTSECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/oauth
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: settings
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: false # enable for debugging
    properties:
      hibernate:
        #dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/data
logging:
  level:
    org.springframework.security: TRACE
